# Generated by Django 3.0.5 on 2021-08-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_result_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attempt',
            field=models.BooleanField(default=False),
        ),
    ]
