# Generated by Django 3.0.5 on 2021-08-01 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_teacher_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='salary',
        ),
    ]
